
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							NEW BLADE
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________

ADD_KIT ~B_LADE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~B_LADE  	        0 0 0 0 1 1 0 1~
~B_LADE                 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_LADE              0  12   0   13   0  15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~B_LADE              0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~B_LADE             0   0   0   0   0  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~B_LADE          0   0   0   0   0  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~B_LADE              1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~B_LADE             0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~%mod_folder%/kits/bard/%version%/B_LADE.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_B_E K_B_H K_B_HE K_B_G K_B_D K_B_HL K_B_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00200000 5~  // Blade useability as normal

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ba0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @500100  //lower
SAY @500101   //mixed
SAY @500102   //desc
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@500103)
		STR_VAR
			kit_name = B_LADE
			hpclass = ~HPPRS~
			clsrcreq = ~1 1 1 0 0 0 0~
	END
END
//____________________________________________________________________________________

//ABILITY FILES_______________________________________________________________
//
