////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////              ENDURANCE                  //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

COPY ~%mod_folder%/data/skills/spl/endure/b_wind2.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @820000
	SAY NAME2 @820000
	SAY UNIDENTIFIED_DESC @820001  //
	SAY IDENTIFIED_DESC @820001  //
/*
COPY ~%mod_folder%/data/skills/spl/b_wind3.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @7
	SAY NAME2 @7
	SAY UNIDENTIFIED_DESC @810054  //
	SAY IDENTIFIED_DESC @810054  //

COPY ~%mod_folder%/data/skills/spl/b_wind4.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @7
	SAY NAME2 @7
	SAY UNIDENTIFIED_DESC @810055  //
	SAY IDENTIFIED_DESC @810055  //

COPY ~%mod_folder%/data/skills/spl/b_wind5.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @7
	SAY NAME2 @7
	SAY UNIDENTIFIED_DESC @810056  //
	SAY IDENTIFIED_DESC @810056  //

COPY ~%mod_folder%/data/skills/spl/b_wind6.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @7
	SAY NAME2 @7
	SAY UNIDENTIFIED_DESC @810057  //
	SAY IDENTIFIED_DESC @810057  //

COPY ~%mod_folder%/data/skills/spl/b_wind7.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @7
	SAY NAME2 @7
	SAY UNIDENTIFIED_DESC @810057  //
	SAY IDENTIFIED_DESC @810057  //

COPY ~%mod_folder%/data/skills/spl/b_wind8.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @7
	SAY NAME2 @7
	SAY UNIDENTIFIED_DESC @810058  //
	SAY IDENTIFIED_DESC @810058  //

COPY ~%mod_folder%/data/skills/spl/b_wind9.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @7
	SAY NAME2 @7
	SAY UNIDENTIFIED_DESC @810059  //
	SAY IDENTIFIED_DESC @810059  //
	
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////                 RUNNING                 //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

COPY ~%mod_folder%/data/skills/spl/b_spri2.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @5
	SAY NAME2 @5
	SAY UNIDENTIFIED_DESC @810060  //
	SAY IDENTIFIED_DESC @810060  //

COPY ~%mod_folder%/data/skills/spl/b_spri3.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @5
	SAY NAME2 @5
	SAY UNIDENTIFIED_DESC @810061  //
	SAY IDENTIFIED_DESC @810061  //

COPY ~%mod_folder%/data/skills/spl/b_spri4.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @5
	SAY NAME2 @5
	SAY UNIDENTIFIED_DESC @810062  //
	SAY IDENTIFIED_DESC @810062  //

COPY ~%mod_folder%/data/skills/spl/b_spri5.spl~ ~override~   // Endurance revised Second Wind
        SAY NAME1 @5
	SAY NAME2 @5
	SAY UNIDENTIFIED_DESC @810063  //
	SAY IDENTIFIED_DESC @810063  //

*/