////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////               USE SCROLLS               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////
/////////// Append stats.ids
//////////////////////////////////////////////////////////////////////////////

APPEND ~STATS.ids~ ~2001%TAB%READ_SCROLLS~         //Read Scrolls
APPEND ~STATS.ids~ ~2002%TAB%MAGE_LEVEL~          //Mage level scroll use
APPEND ~STATS.ids~ ~2006%TAB%PRIEST_LEVEL~          //Priest level scroll use



////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////        Class Description         /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
//TO Do

////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////              Buttons             /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////

//none required

//--------------------------------
//    Use Scroll
//--------------------------------

//scroll based splprot: scroll greater than (only)
	INCLUDE ~B_Kits/lib/splprot_scrolls.tpa~

LAF ADD_EXTENDED_SKILL
INT_VAR
	stat = 2001 //
	name = RESOLVE_STR_REF(@900201)         //USe Scroll
	description = RESOLVE_STR_REF(@900202)  //US description
	opcode = 401 //Modify stat
	visibility = 2 // if value not 0
STR_VAR
	class_include = ~{4, 5}~ //Usable by thief, and bard
	kit_include = ~{}~ //
	kit_exclude = ~{0x400D, 0x400F}~ //Blade and skald excluded
 	stat_exclude = ~{{34, 10, 2}, {38, 9, 2}}~ //stat 2002 at least 1, and int at least 9
END

LAF ADD_EXTENDED_SKILL
INT_VAR
	stat = 2001 //
	name = RESOLVE_STR_REF(@900201)        //USe Scroll
	description = RESOLVE_STR_REF(@900202)  //US description
	opcode = 401 //Modify stat
	visibility = 2 // if value not 0
STR_VAR
	class_include = ~{9, 13, 15}~ //Usable by fighter/thief, mage/thief, and cleric/thief
	kit_include = ~{}~ //
	kit_exclude = ~{0x400D, 0x400F}~ //Blade and skald excluded
 	stat_exclude = ~{{68, 10, 2}, {38, 9, 2}}~ //stat 2002 at least 1, and int at least 9
END

LAF ADD_EXTENDED_SKILL
INT_VAR
	stat = 2001 //
	name = RESOLVE_STR_REF(@900201)         //USe Scroll
	description = RESOLVE_STR_REF(@900202)  //US description
	opcode = 401 //Modify stat
	visibility = 2 // if value not 0
STR_VAR
	class_include = ~{10}~ //fighter/mage/thief
	kit_include = ~{}~ //
	kit_exclude = ~{0x400D, 0x400F}~ //Blade and skald excluded
 	stat_exclude = ~{{69, 10, 2}, {38, 9, 2}}~ //stat 2002 at least 1, and int at least 9
END

// 	stat_exclude = ~{{2002, 1, 2}, {38, 9, 2}}~ //stat 2002 at least 1, and int at least 9

//////////////////
//Functionality
////////////////////////////////////////////////////
//TO DO CONTINUE


///////////////////////////////////////
///////////// STAT 2002 (Allowing USE of Mage Scrolls (give a value of 9 to all mages at level 1)
/////////////////////////////////////////////////////////////////////////////////////////////////
//spl that increments stat 2002 to (at least) 1 so that the thief can add skill to read scroll (applied in clab at level 9, takes effect at level 10 as it should)

//B_USS01.spl - the mage version that allows use of lev 9 scrolls given at lev 1 to ALL mages
COPY ~%mod_folder%/data/extra/use_scroll/B_USS01.spl~ ~override~   //
//priest version
COPY ~%mod_folder%/data/extra/use_scroll/B_USS05.spl~ ~override~   //Sets 2006 to 8 (for base priests)

//This set of spells and effs will set stat 2002 based on value of stat 2001 (i.e. 1 if greater than 0, 2 if 10, 3 if 20, ... 10 if 90+ (each set cumulatively)
COPY ~%mod_folder%/data/extra/use_scroll/B_USS02.spl~ ~override~   //applies the eff
//the eff
COPY ~%mod_folder%/data/extra/use_scroll/B_USS02.eff~ ~override~   //applies B_USS03.spl
//the spl that applies the stat based bonuses to stat 2002 and 2006
COPY ~%mod_folder%/data/extra/use_scroll/B_USS03.spl~ ~override~   //applies the bonus values to 2002 or 2006 based on 2001
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 0 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS04~ END  //If 2001 >0, increment 2002 by 1 (i.e. to use pos 0 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 9 parameter2 = %scr_gr% STR_VAR END  //If 2001 >9, increment 2002 by 1 (i.e. to use 1 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 19 parameter2 = %scr_gr% STR_VAR END  //If 2001 >19, increment 2002 by 1 (i.e. to use 2 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 29 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS04~  END  //If 2001 >29, increment 2002 by 1 (i.e. to use 3 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 39 parameter2 = %scr_gr% STR_VAR END  //If 2001 >39, increment 2002 by 1 (i.e. to use 4 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 49 parameter2 = %scr_gr% STR_VAR END  //If 2001 >49, increment 2002 by 1 (i.e. to use 5 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 59 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS04~  END  //If 2001 >59, increment 2002 by 1 (i.e. to use 6 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 69 parameter2 = %scr_gr% STR_VAR END  //If 2001 >69, increment 2002 by 1 (i.e. to use 7 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 79 parameter2 = %scr_gr% STR_VAR END  //If 2001 >79, increment 2002 by 1 (i.e. to use 8 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 89 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS04~ END  //If 2001 >89, increment 2002 by 1 (i.e. to use 9 level scrolls)
//priest scrolls
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 0 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >0, increment 2006 by 1 (i.e. to use pos 0 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 14 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >14, increment 2006 by 1 (i.e. to use 1 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 29 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >29, increment 2006 by 1 (i.e. to use 2 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 44 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >44, increment 2006 by 1 (i.e. to use 3 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 59 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >59, increment 2006 by 1 (i.e. to use 4 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 74 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >74, increment 2006 by 1 (i.e. to use 5 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 89 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >89, increment 2006 by 1 (i.e. to use 6 level scrolls)
         LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter1 = 99 parameter2 = %scr_gr% STR_VAR match_resource = ~B_USS05~ END  //If 2001 >89, increment 2006 by 1 (i.e. to use 7 level scrolls)

COPY ~%mod_folder%/data/extra/use_scroll/B_USS04.spl~ ~override~   //Increments 2002 by 1 (up to 10x) for mage scrolls
COPY ~%mod_folder%/data/extra/use_scroll/B_USS05.spl~ ~override~   //Increments 2006 by 1 (up to 8x) for priest scrolls
///...WHAT ABOUT DRUID SCROLLS??? SHOULD I DIFFERENTIATE OR JUST ALLOW PRIEST AND DRUID SCROLLS TO BE INTERCHANGABLE????
///WHAT ABOUT PALLY AND RANGER SCROLL USE???


//copy over B_USS02.spl--again, the spl that sets stat 2002 to 1--to override
// COPY ~%mod_folder%/class/thief/skills/read_scroll/B_USS02.spl~ ~override~


////////////////////////////////////////////////////
// change scroll usability and incorporate the skill
////////////////////////////////////////////////////

//TO DO
//add scroll usability to thieves (and any others that can use scrolls)
//2002 mage use (lev 1 scrolls requires 2 points in 2002, +1/level
//NOTES ON CSTOM USABILITY
//1) Make the item usable by all classes, or some subset as desired. (by patching all items of the desired type)
//2) In the clab, apply a spl with a number of 180 effects (I haven't tried 181, but iirc it doesn't work) for each item of said type.
//3) also in the clab, apply a spl using 326 tied to the relevant proficiency (or whatever) that applies a spl using effect 321 that removes the first spl.

//WHAT ABOUT USE ANY ITEM HLA???  Maybe change it so that the thief can apply their use scroll to any other usable magic item?





//--------------------------------
//    Barter
//--------------------------------
//CONTINUE w Barter

/*
//need to make functional
LAF ADD_EXTENDED_SKILL
INT_VAR
	stat = 2003 //Add some specific ids to modifify and check for effects
	name = RESOLVE_STR_REF(@501004)         //Barter
	description = RESOLVE_STR_REF(@501005)  //Barter description
	opcode = 401 //New opcode: Extend stat
	visibility = 3 //Show if skill != 0 and character can put points in skill
STR_VAR
	class_include = ~{4, 5, 9, 10, 13, 15}~ //Usable by thief, fighter/thief, fighter/mage/thief, mage/thief, and cleric/thief and bard
	kit_include = ~{}~ //Anyboy???
	kit_exclude = ~{0x400D, 0x400F}~ //Blade and skald excluded
	stat_exclude = ~{{38, 9, 2},{}}~ //Req Int 9 + NEED TO RESTRICT TO 10+Lev Set an added stat to a specific value for lev 10 thieves and bards (except blades)
END

///////STORES
//Change how stores work so that they can be bartered down.  AAAhh
//TO DO
//
*/

//--------------------------------
//    Use Poison
//--------------------------------

//CONTINUE w USE POISON


LAF ADD_EXTENDED_SKILL
INT_VAR
	stat = 2000 //
	name = RESOLVE_STR_REF(@501006)         //Use Poison
	description = RESOLVE_STR_REF(@501006)  //Use Poison Desc
	opcode = 401 //
	visibility = 2 // if value not 0
STR_VAR
	class_include = ~{4, 9, 10, 13, 15}~ //Usable by thief, fighter/thief, fighter/mage/thief, mage/thief, and cleric/thief
	kit_include = ~{}~ //Not usable by ANYBODY else
	kit_exclude = ~{0x400C}~ //Not usable by swashbuckler
	stat_exclude = ~{}~ //
END

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////                BARD SKILLS              //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////        Class Description         /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
//TO Do

////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////              Buttons             /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////
//Bard button functionality  (req EEex)
///////////////////////////////////////////////////////////
//pick locks
//if EEEx is installed, let's give bards basic thievery
// COPY ~%mod_folder%/lib/M_DEBUG.lua~ ~override~  //debug
 COPY_EXISTING ~EEex_Brd.lua~ ~override~
  SPRINT old @500016//
  SPRINT new @500017//
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (Enable thievery for all bards)

/*
//Probably for a different component (i.e. both the search and stealth)

//class button changes --Put search in 5th slot 
COPY ~%mod_folder%/lib/M_B_BRD.lua~ ~override~

 COPY_EXISTING ~UI.MENU~ ~override~
  SPRINT old @500014//
  SPRINT new @500015//
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (stealth as a alt to search in slot 5)
*/

///////////////////////////////////////////////////////////
//2das  (req EEex)
///////////////////////////////////////////////////////////

APPEND ~THIEFSKL.2da~ ~BARD%TAB%25%TAB%15~ //giving them an actual progression (25 at 1st, 10 at level up)
APPEND ~THIEFSKL.2da~ ~BLADE%TAB%15%TAB%10~ //giving them an actual progression (15 at 1st, 5 at level up)
APPEND ~THIEFSKL.2da~ ~JESTER%TAB%25%TAB%15~ //giving them an actual progression (25 at 1st, 10 at level up)
APPEND ~THIEFSKL.2da~ ~SKALD%TAB%10%TAB%5~ //giving them an actual progression (10 at 1st, 10 at level up)

COPY_EXISTING ~THIEFSCL.2da~ ~override~   //to allow them to put points in pick
  SET_2DA_ENTRY_LATER ~b_lock~ 4 5  100   // Standard Bard
  SET_2DA_ENTRY_LATER ~b_lock~ 3 39  100   // Standard Blade
  SET_2DA_ENTRY_LATER ~b_lock~ 4 39  100   // Standard Blade
  SET_2DA_ENTRY_LATER ~b_lock~ 4 40  100   // Standard Jest
  SET_2DA_ENTRY_LATER ~b_lock~ 4 41  100   // Standard Skald
  SET_2DA_ENTRY_LATER ~b_lock~ 3 41  100   // Standard Skald
//set
  SET_2DA_ENTRIES_NOW ~b_lock~ 1
BUT_ONLY
COPY_EXISTING ~skillbrd.2da~ ~override~ //get rid of auto progression
  SET_2DA_ENTRY_LATER ~b_pick~ 3 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 4 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 5 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 6 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 7 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 8 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 9 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 10 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 11 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 12 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 13 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 14 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 15 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 16 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 17 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 18 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 19 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 20 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 21 1  0   //
  SET_2DA_ENTRY_LATER ~b_pick~ 22 1  0   //
//set
  SET_2DA_ENTRIES_NOW ~b_pick~ 1
BUT_ONLY
COPY_EXISTING ~clasiskl.2da~ ~override~ //get rid of 1st level boni
  SET_2DA_ENTRY_LATER ~b_1pick~ 3 5  0   //
  SET_2DA_ENTRY_LATER ~b_1pick~ 3 39  0   //
  SET_2DA_ENTRY_LATER ~b_1pick~ 3 40 0   //
  SET_2DA_ENTRY_LATER ~b_1pick~ 3 41 0   //
//set
  SET_2DA_ENTRIES_NOW ~b_1pick~ 1
BUT_ONLY

//--------------------------------
//    Bardic Knowledge
//--------------------------------

LAF ADD_EXTENDED_SKILL
INT_VAR
	stat = 2004 //Bardic Knowedge
	name = RESOLVE_STR_REF(@500111)
	description = RESOLVE_STR_REF(@500112)
	opcode = 401 //Modify Lore
	visibility = 1 // iff char can put points into it
STR_VAR
	class_include = ~{5}~ //Bard Only
	kit_include = ~{}~ //none
	kit_exclude = ~{0x400D}~ //Blade excluded
	stat_exclude = ~{}~ //No restrictions
END


///////////////////////////////////////////////////////////////////////////
//give a bonus to lore based on Bardic Knowledge score  (say, +1/10 points)
/////////////////////////////

//TO DO


//////////////////////////////////////////
//  Add Bardic Knowledge checks to dialog
//////////////////////////////////////////
//TO DO

//--------------------------------
//    Performance
//--------------------------------

LAF ADD_EXTENDED_SKILL
INT_VAR
	stat = 2005 //Add some specific ids to modifify and check for effects
	name = RESOLVE_STR_REF(@500113)
	description = RESOLVE_STR_REF(@500114)
	opcode = 401 //New opcode: Extend stat
	visibility = 1 //Display if a character can put points into it
STR_VAR
	class_include = ~{5}~ //Bard Only
	kit_include = ~{}~ //none
	kit_exclude = ~{}~ //
	stat_exclude = ~{}~ //No restrictions
END

/////////////////////////////////////////
//  ADD FUNCTIONALITY
/////////////////////////////////////////
//To do
//Performance should reduce fatigue penalty for bard song (if installed)

//modify songs...somehow



///////////////////////////////////////
///////////// Add all nec abilities to clab
////////////////////////////////////////////////////////////////////////////

//Mages (check for clab...)
//Credit for this code belongs to Aquadrizzt
<<<<<<<< qd_blank_clab_inline.2da
2DA V1.0
****
			1           2           3           4           5           6           7           8           9           10          11          12          13          14          15          16          17          18          19          20     21          22          23          24          25          26          27          28          29          30          31          32          33          34          35          36          37          38          39          40    41      42      43      44             45       46      47      48      49      50
ABILITY1    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****     ****        ****        ****        ****        ****        ****        ****        ****        ****        ****
>>>>>>>>

	ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma01.2da~ BEGIN
	  COPY ~qd_blank_clab_inline.2da~ ~override/clabma01.2da~
	END

 APPEND ~CLABMA01.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA02.2da~ BEGIN
 APPEND ~CLABMA03.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA02.2da~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA03.2da~ BEGIN
 APPEND ~CLABMA03.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA03.2da~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA04.2da~ BEGIN
 APPEND ~CLABMA04.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA04.2da~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA05.2da~ BEGIN
 APPEND ~CLABMA05.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA05.2da~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA06.2da~ BEGIN
 APPEND ~CLABMA06.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA06.2da~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA07.2da~ BEGIN
 APPEND ~CLABMA07.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA07.2da~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA08.2da~ BEGIN
 APPEND ~CLABMA08.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA08.2da~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA09.2da~ BEGIN
 APPEND ~CLABMA09.2da~ ~NEW_SKILLS    AP_B_USS01  ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END ELSE
BEGIN
  COPY_EXISTING ~CLABMA01.2da~ ~override/CLABMA09.2da~
END

//Base Thief
APPEND ~CLABTH01.2da~ ~NEW_SKILLS    ****    ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
//base bard
APPEND ~CLABBA01.2da~ ~NEW_SKILLS    ****    ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~

//thansk subtle

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 10 rows
  FOR (row = 3 ; row < rows ; ++row) BEGIN
	READ_2DA_ENTRY %row% 1 10 modname
	READ_2DA_ENTRY %row% 5 10 modclab
	READ_2DA_ENTRY %row% 8 10 modclass
	PATCH_IF (%modclass% = 4)/* && NOT (%modname% STRING_MATCHES_REGEXP ~C0SA+~ = 0) */ OR
                 (%modclass% = 5)/* && NOT (%modname% STRING_MATCHES_REGEXP ~C0SA+~ = 0) */ BEGIN   //thief or bard kits
	  INNER_ACTION BEGIN
		APPEND ~%modclab%.2da~ ~NEW_SKILLS    ****    ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	  END
	END
  END
BUT_ONLY